# Generated by Django 5.0.3 on 2024-03-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_stupid',
            field=models.BooleanField(default=True),
        ),
    ]
